# Generated by Django 6.0.6 on 2026-06-09 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='프로젝트명')),
                ('company_name', models.CharField(max_length=200, verbose_name='업체명')),
                ('issuing_org', models.CharField(blank=True, max_length=200, verbose_name='발주기관')),
                ('budget', models.CharField(blank=True, max_length=100, verbose_name='사업 예산')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='계약 담당자')),
                ('status', models.CharField(choices=[('reviewing', '계약 검토중'), ('in_progress', '이행중'), ('completed', '완료')], default='reviewing', max_length=20, verbose_name='상태')),
                ('requirements_doc', models.FileField(blank=True, null=True, upload_to='contracts/requirements/', verbose_name='요구사항정의서')),
                ('rfp_doc', models.FileField(blank=True, null=True, upload_to='contracts/rfp/', verbose_name='RFP(제안요청서)')),
                ('contract_doc', models.FileField(blank=True, null=True, upload_to='contracts/contract/', verbose_name='계약서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '계약',
                'verbose_name_plural': '계약 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('requirements', '요구사항정의서'), ('rfp', 'RFP (제안요청서)'), ('contract', '계약서')], max_length=30, verbose_name='문서 유형')),
                ('file', models.FileField(upload_to='contracts/docs/', verbose_name='파일')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='원본 파일명')),
                ('review_status', models.CharField(choices=[('pending', '미검토'), ('reviewed', '검토완료')], default='pending', max_length=20, verbose_name='검토 상태')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract')),
            ],
            options={
                'verbose_name': '계약 문서',
                'verbose_name_plural': '계약 문서 목록',
            },
        ),
        migrations.CreateModel(
            name='AIReviewResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blanks', models.JSONField(default=list, verbose_name='빈칸/미기재')),
                ('typos', models.JSONField(default=list, verbose_name='오탈자')),
                ('legal_issues', models.JSONField(default=list, verbose_name='법률 관련')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_result', to='contracts.contractdocument')),
            ],
            options={
                'verbose_name': 'AI 검토 결과',
            },
        ),
    ]
