# Generated by Django 6.0.5 on 2026-07-02 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0002_contract_contract_end_contract_contract_start"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFPParsedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parsed_json", models.JSONField(blank=True, default=dict)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("processing", "처리중"),
                            ("done", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfp_parsed",
                        to="contracts.contractdocument",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFP 파싱 결과",
                "verbose_name_plural": "RFP 파싱 결과 목록",
            },
        ),
    ]
