# Generated by Django 6.0.5 on 2026-07-10 08:10

from django.db import migrations


def backfill_done_status(apps, schema_editor):
    """0005에서 status 필드가 추가되면서 기존 행은 전부 default인 'idle'이 됐다.
    하지만 이 필드가 생기기 전 코드는 analyze_document_task가 끝날 때만
    AIReviewResult를 만들었으므로, 기존에 있던 행은 전부 이미 완료된 분석 결과다.
    'idle' 그대로 두면 분석화면이 "분석 시작" 버튼을 다시 보여주며 완료된
    결과를 안 보여주게 된다.
    """
    AIReviewResult = apps.get_model("contracts", "AIReviewResult")
    AIReviewResult.objects.filter(status="idle").update(status="done")


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0005_aireviewresult_started_at_aireviewresult_status_and_more"),
    ]

    operations = [
        migrations.RunPython(backfill_done_status, migrations.RunPython.noop),
    ]
