# Generated by Django 6.0.6 on 2026-06-09 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='contracts.contract')),
            ],
            options={
                'verbose_name': '이행 관리',
                'verbose_name_plural': '이행 관리 목록',
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_type', models.CharField(choices=[('kickoff', '착수보고서'), ('test_plan', '테스트 계획서'), ('test_result', '테스트 결과 보고서'), ('final', '완료보고서')], max_length=20, verbose_name='산출물 유형')),
                ('file', models.FileField(blank=True, null=True, upload_to='performance/deliverables/', verbose_name='파일')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='원본 파일명')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='제출 예정일')),
                ('submitted_date', models.DateField(blank=True, null=True, verbose_name='실제 제출일')),
                ('status', models.CharField(choices=[('pending', '미등록'), ('submitted', '제출완료')], default='pending', max_length=20, verbose_name='상태')),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='performance.performance')),
            ],
            options={
                'verbose_name': '산출물',
                'verbose_name_plural': '산출물 목록',
                'ordering': ['deliverable_type'],
            },
        ),
    ]
