# Generated by Django 6.0.5 on 2026-06-29 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverable",
            name="deliverable_type",
            field=models.CharField(
                choices=[
                    ("kickoff", "사업수행계획서"),
                    ("tech_apply", "기술 적용 결과표"),
                    ("final", "사업추진결과보고서"),
                ],
                max_length=20,
                verbose_name="산출물 유형",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255, verbose_name="메시지")),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="/performance/",
                        max_length=255,
                        verbose_name="이동 경로",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="읽음 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "알림",
                "verbose_name_plural": "알림 목록",
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
