# Generated by Django 6.0.5 on 2026-07-06 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_rfpparseddata"),
        ("performance", "0002_alter_deliverable_deliverable_type_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverable",
            name="deliverable_type",
            field=models.CharField(
                choices=[
                    ("kickoff", "사업수행계획서"),
                    ("tech_apply", "기술적용결과표"),
                    ("final", "사업추진결과보고서"),
                ],
                max_length=20,
                verbose_name="산출물 유형",
            ),
        ),
        migrations.CreateModel(
            name="ExecutionPlanParsedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parsed_json", models.JSONField(blank=True, default=dict)),
                (
                    "qa_report",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="QA 검수 리포트"
                    ),
                ),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("processing", "처리중"),
                            ("done", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "deliverable",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsed_data",
                        to="performance.deliverable",
                    ),
                ),
            ],
            options={
                "verbose_name": "과업수행계획서 파싱 결과",
                "verbose_name_plural": "과업수행계획서 파싱 결과 목록",
            },
        ),
        migrations.CreateModel(
            name="RFPComparisonResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comparison_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution_plan_parsed",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="performance.executionplanparseddata",
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfp_comparisons",
                        to="performance.performance",
                    ),
                ),
                (
                    "rfp_parsed",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contracts.rfpparseddata",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFP 비교 결과",
                "verbose_name_plural": "RFP 비교 결과 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
