# Generated by Django 6.0.5 on 2026-07-06 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_alter_deliverable_deliverable_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechApplyCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('deliverable', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_apply_result', to='performance.deliverable')),
            ],
            options={
                'verbose_name': '기술적용결과표 검증 결과',
                'verbose_name_plural': '기술적용결과표 검증 결과 목록',
            },
        ),
    ]
