# Generated by Django 6.0.5 on 2026-06-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_session_key",
            field=models.CharField(
                blank=True, max_length=40, null=True, verbose_name="현재 세션키"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="연속 로그인 실패 횟수"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="force_password_change",
            field=models.BooleanField(
                default=True, verbose_name="다음 로그인 시 비밀번호 변경"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="lock_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FAILED_LOGIN", "로그인 5회 연속 실패"),
                    ("PASSWORD_EXPIRED", "비밀번호 90일 만료"),
                    ("ADMIN", "관리자 잠금"),
                ],
                max_length=30,
                verbose_name="잠금 사유",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="잠금 일시"),
        ),
        migrations.AddField(
            model_name="user",
            name="password_changed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="비밀번호 변경 일시"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(max_length=100, verbose_name="부서"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="이메일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="이름"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="성"),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.CharField(max_length=100, verbose_name="소속기관"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="전화번호"),
        ),
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.CharField(max_length=50, verbose_name="직급"),
        ),
    ]
