# Generated by Django 6.0.5 on 2026-06-30 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_step4_cleanup_legacy_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "ordering": ["name"],
                "verbose_name": "소속부서",
                "verbose_name_plural": "소속부서 목록",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="소속부서(미사용, deprecated)"
            ),
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="접속 IP"
                    ),
                ),
                ("success", models.BooleanField(verbose_name="성공 여부")),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="User-Agent"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="접속 일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "접속기록",
                "verbose_name_plural": "접속기록 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
