# Generated by Django 6.0.5 on 2026-07-08 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20260630_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', '조회'), ('upload', '업로드'), ('delete', '삭제')], max_length=20, verbose_name='행위')),
                ('target_type', models.CharField(max_length=50, verbose_name='대상 유형')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='대상 ID')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='상세')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='접속 IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발생 일시')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.organization', verbose_name='소속부서')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='행위자')),
            ],
            options={
                'verbose_name': '감사 로그',
                'verbose_name_plural': '감사 로그 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
