"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.
"""
from dotenv import load_dotenv
load_dotenv()

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-8ss%o!+fz+rxppl%&)j!8i^--w-=7-e%f7=jt49%v$a4x8)9_l"
DEBUG = True
ALLOWED_HOSTS = []

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "accounts",
    "contracts",
    "performance",
    "django_celery_results",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "accounts.middleware.AccountSecurityMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 8},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
    {
        "NAME": "accounts.validators.EnglishNumberSpecialCharacterValidator",
    },
]

LANGUAGE_CODE = "ko-kr"
TIME_ZONE = "Asia/Seoul"
USE_I18N = True
USE_TZ = True

AUTH_USER_MODEL = "accounts.User"
LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"

WORKIT_INSTITUTION_NAME = "행정안전부"

# 계정 보안 정책
ACCOUNTS_INITIAL_PASSWORD = "Workit2026!"
ACCOUNTS_MAX_FAILED_LOGIN_ATTEMPTS = 5
ACCOUNTS_PASSWORD_MAX_AGE_DAYS = 90
# KILL_OLD: 신규 로그인 성공 시 기존 세션 종료 / BLOCK_NEW: 기존 세션이 있으면 신규 로그인 차단
ACCOUNTS_SINGLE_SESSION_POLICY = "KILL_OLD"

# 30분 비활동 자동 로그아웃
SESSION_COOKIE_AGE = 30 * 60
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Celery 설정
CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_RESULT_BACKEND = "django-db"
CELERY_CACHE_BACKEND = "django-cache"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

CELERY_BROKER_TRANSPORT_OPTIONS = {
    "socket_connect_timeout": 10,
    "socket_timeout": 10,
}
CELERY_REDIS_SOCKET_CONNECT_TIMEOUT = 10

# 이메일 설정
import os
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = f'Workit <{os.environ.get("EMAIL_HOST_USER")}>'

# 로깅 설정
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'loggers': {
        # pdfminer(pdfplumber/pdf2image 등이 내부적으로 사용)는 폰트 디스크립터에
        # FontBBox가 없거나 형식이 이상한 PDF를 만나면 WARNING을 남기는데, 실제
        # 텍스트 추출 결과에는 영향이 없는 흔한 PDF 생성기 특성이라 로그만 시끄러워진다.
        # ERROR 이상만 남기도록 낮춘다 (실제 파싱 실패는 우리 쪽 코드가 별도로 예외 처리함).
        'pdfminer': {'level': 'ERROR'},
    },
}